### ISSUE TITLE
Merge vdsuite NID database to the vitasdk

### ISSUE THREAD

**Issue by devnoname120** [vitasdk/vita-headers#574]
Follow-up of https://github.com/vitasdk/vita-headers/pull/390.

https://bin.shotatoshounenwachigau.moe/vdsuite/ghidra-loader-db.yml

**Comment by Princess-of-Sleeping** [comment]
I disagree with this.
Above all, vitasdk and vdsuite db already use different function names.
And added by using script -> vitasdk to broken again.

**Comment by devnoname120** [comment]
I won't overwrite function names where it doesn't make sense.
My previous iteration (https://github.com/vitasdk/vita-headers/pull/390) that merged 3 databases didn't cause any regressions and didn't break any homebrews compilation.

**Comment by Princess-of-Sleeping** [comment]
known problem

1. vdsuite uses the official name as much as possible, but vitasdk does not.
This case, Which would you choose?

2. Removed "k" sce.
vdsuite decided to use sce instead of ksce even for kernel functions. So need update Travis script.

But, if you ignore 1 and 2 and added them, everything will be mixed and maintenance will be very difficult.

**Comment by Princess-of-Sleeping** [comment]
And you made the wrong addition using a script.
https://github.com/vitasdk/vita-headers/pull/390/files#diff-f18ad1cb18f3d08fc815f05fda7da0ed3d15e0b2acd35e20e64c0ad9bc02697cR473-R483

**Comment by devnoname120** [comment]
Both 1 and 2 are covered in the script: https://www.github.com/devnoname120/vitasdk-db-tools/tree/master/dbtools.py

It uses a `db_lookup.yml` file as a reference to make sure to add to the right modules/libraries and ignore all the unknown NIDs.

Which function was incorrectly added?

**Comment by Princess-of-Sleeping** [comment]
```
      SceAppUtilBook:
        nid: 0xDA27A9D3
        kernel: true
        functions:
          ksceAppUtilBookMount: 0xFDAAF091
          ksceAppUtilBookUmount: 0x9C1794C2
      SceAppUtilAddcontForce:
        nid: 0x9D061921
        kernel: true
        functions:
          ksceAppUtilAddcontForceAddcontMount: 0x6087E5F7
```
These functions are user functions, but in pull/390 they were added as kernel functions.
